# Basic
name:               "Haresh Khanna"

author:
  facebook:         hareshkhanna01
  youtubeUser:      your-id
  youtubeChannel:   your-id
  twitter:          haresh_kh
  github:           hareshkh
  stackoverflow:    5920372/haresh-khanna
  quora:            your-id
  linkedin:         hareshkh
  pinterest:        your-id
  googlePlus:       +HareshKhanna
  instagram:        haresh_khanna
  reddit:           hareshkh
  medium:           hareshkhanna
  tumblr:           your-id
  email:            khanna.haresh@yahoo.co.in

copyright:
  year:             2017
  name:             Haresh

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "hareshkhanna"

# URL
url:                "https://hareshkh.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/blog" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Calcutta
permalink:          /:year/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/hareshkh"
  - name:           "Resume"
    url:            "/resume.pdf"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]